services:
  # PostgreSQL database for LangGraph and metadata
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aegra
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d aegra"]
      interval: 5s
      timeout: 5s
      retries: 5
  ollama:
    image: ollama/ollama:0.12.4-rc4
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 5s
      timeout: 3s
      retries: 5
    # Aegra Server
  aegra:
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    networks:
      - backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/aegra
      - AUTH_TYPE=noop
      - DEBUG=true
      - PORT=${PORT:-8000}
      - OLLAMA_API_BASE=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./aegra.json:/app/aegra.json:ro
      - ./graphs:/app/graphs:ro
      - ./src:/app/src:ro # for hot reload support of server
      - ./auth.py:/app/auth.py:ro
      - ./.env:/app/.env:ro
      - ./alembic:/app/alembic:ro # for migrations
    command: >
      sh -c "
        echo 'Running database migrations...' &&
        alembic upgrade head &&
        echo 'Starting Aegra server...' &&
        uvicorn src.agent_server.main:app --host 0.0.0.0 --port $${PORT:-8000} --reload
      "

  # Redis (optional - for advanced queuing in future phases)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis_data:/data
    profiles:
      - redis
networks:
  backend:
    driver: bridge # It allow all of them to communicate with each other  
volumes:
  postgres_data:
  redis_data:
  ollama_models:
